### PR TITLE
Include MIT license in the repository.

### PR DESCRIPTION
**Pull request by brouberol**
I added a copy of the GPLv3 license in the repository itself, as I should have done months/years ago.

### CODE REVIEW

**Comment by erjiang** [comment]
Does this mean that any software using the haversine module must also be released under the GPLv3? Those are quite onerous terms for a small Python module. Maybe you could consider the LGPL instead?

**Comment by jdeniau** [comment]
I read a little more on the subject and your were right yesterday @brouberol , GPL license is useless if you want to use a package in a closed app.

We should release this package in MIT License.

**Comment by brouberol** [comment]
MIT it is. Give me a couple of minutes to update the PR. Do you want me to update the package version, so that you can send a new release to PyPI?

**Comment by brouberol** [comment]
The license was updated from GPLv3 to MIT. I cannot help but feel good about it. GPLv3 was a personal choice of mine a while back, but I tend to find it too extreme now.

@jdeniau, you might want to bump the version before releasing the newly licensed package to PyPI, and also maybe add your name and email as maintainer, as I don't have write access on the repo anymore.

Have a look at the [distutils dociumentation](https://docs.python.org/3.4/distutils/setupscript.html#additional-meta-data) for more information.

**Comment by jdeniau** [comment]
The package is updated in PyPI in version 0.4.0

**Pull request merged**
