### PR TITLE
Adds normalization of lat/lon to their corresponding ranges

### PR DESCRIPTION
**Pull request by merschformann**
# Description

Adds normalization of lat/lon values outside the allowed ranges. I.e., latitude values outside of [-90,90] and longitude values outside of [-180,180] will be moved into the corresponding range.

This behavior is debated in #49. Another alternative would be to simply throw an exception on lat outside of [-90,90] or lon outside of [-180,180]. Hence, feel free to reject and use a different option.

## Notes

- The test expectations had to be slightly adjusted due to numerical issues

### CODE REVIEW

**Comment by merschformann** [comment]
There seems to be a dependency installation error unrelated to the changes here. I also get it locally on the main branch and first commits still succeeded.

I can reproduce on main branch when running `pipenv install --dev`.

:thinking:

**Comment by jdeniau** [comment]
The dependency issue is probably due to https://github.com/untitaker/python-atomicwrites/issues/61

I don't even know why is this package used ¯\_(ツ)_/¯

**Comment by jdeniau** [comment]
It seems that atomicwrites has been used by pytest, and removed in https://github.com/pytest-dev/pytest/pull/10115. I will try to fix the build

**Comment by jdeniau** [comment]
@merschformann The dependency issue is fixed. I updated your branch, but it seems that you now have an assertion error in your test.

**Comment by merschformann** [comment]
@jdeniau Thanks for fixing! :heart: 

> Personally I'm not really fan of the normalize parameter, but as you two probably use more haversine than I do, I'll let you choose.

I also don't have a strong opinion at all. I think I lean towards only raising the exception on improper lat/lon inputs a little. It would keep the code base simpler. But I'd like to defer to others on making the final call. (ping @uri-rodberg and who else is interested) 

However, I am happy to quickly adapt the PR after we come to a decision.

**Comment by uri-rodberg** [comment]
> @uri-rodberg What do you think of this ?

Personally I think it's a good idea to let the user decide if to raise an exception or normalize lat/lon. So I prefer to keep it this way.

I would also add the following tests:

```python
    with pytest.raises(ValueError):
        haversine((-90.0001, 0), (0, 0), Unit.DEGREES)
    with pytest.raises(ValueError):
        haversine((0, 0), (90.0001, 0), Unit.DEGREES)
    with pytest.raises(ValueError):
        haversine((0, -180.0001), (0, 0), Unit.DEGREES)
    with pytest.raises(ValueError):
        haversine((0, 0), (0, 180.0001), Unit.DEGREES)
```
(use default value for `normalize`)

And:
```python
# assert that haversine((-90.0001, 0), (0, 0), Unit.DEGREES, normalize=True) == haversine((-89.9999, 180), (0, 0), Unit.DEGREES, normalize=True) # or that the difference between them is very close to 0
# assert that haversine((-90.0001, 30), (0, 0), Unit.DEGREES, normalize=True) == haversine((-89.9999, -150), (0, 0), Unit.DEGREES, normalize=True) # or that the difference between them is very close to 0
# Also check haversine((0, 0), (90.0001, 0), Unit.DEGREES, normalize=True)
# Also check haversine((0, 0), (90.0001, 30), Unit.DEGREES, normalize=True)
# Also check haversine((0, -180.0001), (0, 0), Unit.DEGREES, normalize=True)
# Also check haversine((30, -180.0001), (0, 0), Unit.DEGREES, normalize=True)
# Also check haversine((0, 0), (0, 180.0001), Unit.DEGREES, normalize=True)
# Also check haversine((0, 0), (30, 180.0001), Unit.DEGREES, normalize=True)
```

**Comment by merschformann** [comment]
Added the test cases. Please check whether I understood them correctly and let me know, if something is missing. :relaxed:

**Comment by uri-rodberg** [comment]
> Added the test cases. Please check whether I understood them correctly and let me know, if something is missing. ☺️

Thanks, it looks fine to me.

**Comment by uri-rodberg** [comment]
Just a question - why do you use `179.99990000000003` and not `179.9999`?

**Comment by merschformann** [comment]
I was expecting numerical issues, since we're checking equality. Apparently, it's not necessary.
Also, I agree that using `pytest.approx` would be cleaner in that case.

**Comment by merschformann** [comment]
Let me cleanup the test cases a bit in general...

**Comment by jdeniau** [comment]
Thanks to both of you, this has been released as `2.6.0`

**Pull request merged**
